version: 2

sources:
  - name: raw 
    schema: gz_raw_data 
    description: Le dataset
    tables : 
    - name: product
      identifier: raw_gz_product
      description: purchase price by products
      columns:
        - name: products_id
          description: primary key
          tests:
            - unique
            - not_null
            
    - name: sales
      identifier: raw_gz_sales
      description: sales by dates with each products and quantity by orders
      tests: 
        - unique:
            column_name: "(orders_id || '-' || pdt_id)"
      loaded_at_field: CAST(date_date AS DATE)
      freshness:
        warn_after: 
          count: 90
          period: day
        error_after:
          count: 365
          period: day
      columns:
        - name: date_date
          description: date of purchase
        - name: orders_id
          description: primary key 1
        - name: products_id
          description: primary key 2
        - name: revenue
          description: turnover by order
        - name: quantity
          description: number of products by orders
        - name: products_id
          description: primary key 2

    - name: ship
      identifier: raw_gz_ship
      columns:
        - name: orders_id
          description: primary key de ship
          tests: 
            - unique
            - not_null
    - name: facebook
      identifier: raw_gz_facebook
      description: campaign with facebook
      columns: 
        - name: date_date
          description: pk 
        - name: campaign_name
          description: name 
        - name: paid_source
          description: source of the campaign 
        - name: campaign_key
          description: id of the campaign, pk
        - name: ads_cost
          description: price of the campaign 
        - name: impression
          description: nb of people who saw the campaign 
        - name: click
          description: nb of people who clicked on the campaign
      tests: 
        - unique:
            column_name: "(date_date|| '-' || campaign_key)"  
    - name: criteo
      identifier: raw_gz_criteo
      description: campaign with criteo
      columns:
        - name: date_date
          description: pk 
        - name: campaign_name
          description: name 
        - name: paid_source
          description: source of the campaign 
        - name: campaign_key
          description: id of the campaign, pk
        - name: ads_cost
          description: price of the campaign 
        - name: impression
          description: nb of people who saw the campaign 
        - name: click
          description: nb of people who clicked on the campaign
      tests:
        - unique:
            column_name: "(date_date|| '-' || campaign_key)"                
    - name: bing
      identifier: raw_gz_bing
      description: campaign with bing
      columns:
        - name: date_date
          description: pk 
        - name: campaign_name
          description: name 
        - name: paid_source
          description: source of the campaign 
        - name: campaign_key
          description: id of the campaign, pk
        - name: ads_cost
          description: price of the campaign 
        - name: impression
          description: nb of people who saw the campaign 
        - name: click
          description: nb of people who clicked on the campaign
      tests:
        - unique:
            column_name: "(date_date|| '-' || campaign_key)" 
    - name: adwords
      identifier: raw_gz_adwords
      description: campaign with adwords
      columns:
        - name: date_date
          description: pk 
        - name: campaign_name
          description: name 
        - name: paid_source
          description: source of the campaign 
        - name: campaign_key
          description: id of the campaign, pk
        - name: ads_cost
          description: price of the campaign
        - name: impression
          description: nb of people who saw the campaign 
        - name: click
          description: nb of people who clicked on the campaign
      tests:
        - unique:
            column_name: "(date_date|| '-' || campaign_key)" 



